"""为两份现有人工验收包生成易读的单题静态页面；原始 HTML 只备份一次。"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
RESULTS = ROOT / "results"
ACCEPTANCE = RESULTS / "multimodal_data_20260925" / "human_acceptance"
ASSETS = Path(__file__).parent
TRANSLATIONS = RESULTS / "review_ui_20260926" / "query_translations.json"
PACKAGES = ("natural100_seed2026", "correspondence100_seed2026")


def original(path: Path) -> str:
    backup = path.with_name(path.stem + ".original_20260926.html")
    if not backup.exists():
        backup.write_bytes(path.read_bytes())
    return backup.read_text(encoding="utf-8")


def page(package: str, translations: dict[str, str]) -> None:
    path = ACCEPTANCE / package / "review.html"
    source = original(path)
    if package == "correspondence100_seed2026":
        source = source.replace("<img src=", "<img loading=\"lazy\" src=")
    assert source.count("</body>") == 1, path
    css = (ASSETS / "review_ui_20260926.css").read_text(encoding="utf-8")
    js = (ASSETS / "review_ui_20260926.js").read_text(encoding="utf-8")
    payload = json.dumps(translations, ensure_ascii=False).replace("<", "\\u003c")
    injected = (
        "\n<!-- Generated by code/tools/build_review_ui_20260926.py; original HTML preserved alongside. -->\n"
        f"<style id=\"review-ui-20260926-style\">\n{css}\n</style>\n"
        f"<script id=\"review-ui-20260926-script\">\n"
        f"const REVIEW_UI_KIND={json.dumps(package)};\n"
        f"const REVIEW_UI_TRANSLATIONS={payload};\n{js}\n</script>\n"
    )
    path.write_text(source.replace("</body>", injected + "</body>"), encoding="utf-8", newline="\n")


def entrance() -> None:
    path = RESULTS / "same_day_multimodal_pilot_20260926" / "index.html"
    original(path)
    path.write_text("""<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>人工验收 · RGBDT 首包</title>
<style>
:root{color-scheme:light;--ink:#1c2b2d;--muted:#58696c;--line:#dce5e3;--accent:#176b62}*{box-sizing:border-box}
body{margin:0;background:#f4f6f5;color:var(--ink);font:16px/1.6 "Segoe UI","Microsoft YaHei",system-ui,sans-serif}
main{max-width:920px;margin:0 auto;padding:44px 20px 70px}h1{font-size:clamp(30px,5vw,42px);line-height:1.25;margin:0 0 14px}h2{font-size:20px;margin:0 0 8px}p{margin:0 0 14px;color:var(--muted)}
.tag{color:var(--accent);font-weight:700;font-size:14px;letter-spacing:.05em}.intro{font-size:18px;max-width:760px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:28px 0}
.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:25px;box-shadow:0 4px 18px #1c3c3608}.card strong{font-size:14px;color:var(--accent)}.card p{min-height:52px}.card a{display:inline-block;background:var(--accent);color:white;text-decoration:none;font-weight:700;border-radius:8px;padding:11px 17px}.card a:hover{background:#12574f}
.help{background:#fff;border:1px solid var(--line);border-radius:12px;padding:22px 25px}.help ol{margin:8px 0;padding-left:22px}.help li{padding:4px 0}.more{margin-top:25px;color:var(--muted);font-size:14px}.more a{color:var(--accent)}
@media(max-width:700px){main{padding:24px 16px}.cards{grid-template-columns:1fr}.card p{min-height:0}}
</style></head><body><main>
<div class="tag">AIC · RGBDT 多模态数据</div><h1>人工验收，从这里开始</h1>
<p class="intro">先看图、读描述，再逐条作出自己的判断。两份页面分别检查描述是否准确，以及 RGB 与红外／深度图中的对象是否对应。</p>
<div class="cards">
<section class="card"><strong>100 条 · 描述检查</strong><h2>自然描述验收</h2><p>判断描述是否正确，且只指向一个目标。可参考 RGB、红外、深度预览与原 RGB 提议框。</p><a href="../multimodal_data_20260925/human_acceptance/natural100_seed2026/review.html">打开描述检查</a></section>
<section class="card"><strong>100 条 · 图像对应检查</strong><h2>跨模态对应验收</h2><p>并排比较 RGB 与辅助图的原图和提议框，检查是否为同一对象、范围是否一致。</p><a href="../multimodal_data_20260925/human_acceptance/correspondence100_seed2026/review.html">打开对应检查</a></section>
</div>
<section class="help"><h2>怎么保存结果</h2><ol><li>选择判定后，草稿会保存在当前浏览器；刷新页面可继续。备注可选。</li><li>每份页面完成后，点击“导出 CSV”，分别保存下载文件。两个包的文件名不同，原始 CSV 不会被改动。</li><li>如果换电脑或浏览器，用同一页的“导入 CSV”恢复已下载的结果。</li></ol><p>可以先完成一部分再导出；未判定项目保持空白。深度灰度图只用于视觉对应核查，不能据亮暗推断真实距离。</p></section>
<p class="more">更多材料：<a href="../multimodal_data_20260925/human_acceptance/index.html">其他四份验收包</a> · <a href="README.md">首包说明与结果转换步骤</a>。首包当前有 252 条待验收输出任务；两份页面最多覆盖其中 186 条。页面上的判定不会直接放行训练数据。</p>
</main></body></html>
""", encoding="utf-8", newline="\n")


def main() -> None:
    translations = json.loads(TRANSLATIONS.read_text(encoding="utf-8")) if TRANSLATIONS.exists() else {}
    if not isinstance(translations, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in translations.items()):
        raise ValueError("query_translations.json 必须是英文原文到中文译文的字符串字典")
    for package in PACKAGES:
        page(package, translations)
    entrance()
    print(f"已生成两份 100 条验收页和统一入口；可用译文 {len(translations)} 条。")


if __name__ == "__main__":
    main()
